VERSION="2.5.0"

[DOCUMENTATION]
ORG_NAME="XPlosion Token"
ORG_URL="https://xplosion.fun"
ORG_LOGO="https://xplosion.fun/assets/xplosion-logo.png"
ORG_DESCRIPTION="XPlosion (XPLO) is the most explosive token on the Stellar network, designed for rapid gains and high momentum trading."

[[CURRENCIES]] 
code="XPLO"
issuer="GBUGKQMLVIIDFFWH6GB5T7TSWCZNZPBOMEGZK3XT655QXRCH5EPEZYVL"
status="live"
display_decimals=5
name="XPLO"
fixed_number=30000000000
desc="XPLO is a blockchain asset on the Stellar network by xplosion, designed for entertainment and rapid gains"
conditions="Maximum supply of XPLO is 30B tokens only"
image="https://trumpstellar.digital/assets/XPLO.gif"
