VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="XPlosion Token"
ORG_URL="https://xplosion.fun"
ORG_LOGO="https://xplosion.fun/assets/xplosion-logo.png"
ORG_DESCRIPTION="XPlosion (XPLO) is the most explosive token on the Stellar network, designed for rapid gains and high momentum trading."

